# Generated by Django 4.1.3 on 2022-11-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cart_item_cart_quantity_item_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='count',
            field=models.IntegerField(),
        ),
    ]
